server:
  port: 5500
host:
  zkserver: 127.0.0.1
  rdserver: 127.0.0.1
  dbserver: 120.78.193.62
  mqserver: 127.0.0.1
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${host.dbserver}:3306/zc?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: fuyi
    password: 950613
    driver-class-name: com.mysql.jdbc.Driver